title: Em Powered
author: Emily Scarpitti
email: escarpitti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developed by me. 
  
# social links
twitter_username: escarpitti # DO NOT include the @ character, or else the build will fail!
github_username:  escarpitti # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
